# Generated by Django 5.2.14 on 2026-05-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0002_ejercicio_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='video_url',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ejercicios/videos/'),
        ),
    ]
