# Generated by Django 5.2.14 on 2026-05-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0003_remove_ejercicio_video_url_ejercicio_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ejercicios/'),
        ),
    ]
