# Generated by Django 5.2.14 on 2026-05-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0004_alter_ejercicio_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='video',
            field=models.FileField(blank=True, default='ejercicios/ejemplo.mp4', null=True, upload_to='ejercicios/'),
        ),
    ]
