# Generated by Django 6.0.3 on 2026-04-07 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proteina', models.IntegerField()),
                ('calorias', models.IntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('alergia', models.ManyToManyField(related_name='alergia', to='recetas.alergia')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autor', to=settings.AUTH_USER_MODEL)),
                ('objetivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivo', to='recetas.objetivo')),
            ],
        ),
    ]
