# Generated by Django 5.2.14 on 2026-05-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
