# Generated by Django 5.2.14 on 2026-05-16 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_receta_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='video_url',
        ),
        migrations.AddField(
            model_name='receta',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='recetas/videos/'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='alergia',
            field=models.ManyToManyField(related_name='recetas', to='recetas.alergia'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receta',
            name='objetivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='recetas.objetivo'),
        ),
    ]
