# Generated by Django 5.2.14 on 2026-05-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_remove_receta_video_url_receta_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='recetas/'),
        ),
    ]
