# Generated by Django 6.0.3 on 2026-03-18 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGimnasio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gimnasio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('provincia', models.CharField(max_length=20)),
                ('localidad', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('tipo_gimnasio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gimnasios', to='gimnasios.tipogimnasio')),
            ],
        ),
    ]
