# Generated by Django 5.2.14 on 2026-05-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasios', '0004_alter_gimnasio_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gimnasio',
            name='video',
        ),
        migrations.AddField(
            model_name='gimnasio',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
